git:
  username: bbakernoaa
  email: "barry.baker@noaa.gov"
hpc_domains: 
  hera:
    username: Barry.Baker
    port: 53612
    domain:
      - "hera-rsa.princeton.rdhpcs.noaa.gov"
      - "hera-rsa.boulder.rdhpcs.noaa.gov"
  gaea:
    username: Barry.Baker
    domain:
      - "gaea-rsa.princeton.rdhpcs.noaa.gov"
      - "gaea-rsa.boulder.rdhpcs.noaa.gov"
  hopper:
    username: bbaker25
    domain: 
      - "hopper.orc.gmu.edu"
  aaqest:
    username: barryb
    domain:
      - "aaqest.arl.noaa.gov"
  byun:
    username: barryb
    domain:
      - "byun.arl.noaa.gov"
