[git]
username = "bbakernoaa"
email = "barry.baker@noaa.gov"

[hpc_domains]

## Hera Configuration
[hpc_domains.hera]
username = "Barry.Baker"
port = 53612
domain = ["hera-rsa.princeton.rdhpcs.noaa.gov", "hera-rsa.boulder.rdhpcs.noaa.gov"]

## Gaea Configuration
[hpc_domains.gaea]
username = "Barry.Baker"
domain = ["gaea-rsa.princeton.rdhpcs.noaa.gov", "gaea-rsa.boulder.rdhpcs.noaa.gov"]

## Hopper Configuration
[hpc_domains.hopper]
username = "bbaker25"
domain = ["hopper.orc.gmu.edu"]

## Aaqest Configuration
[hpc_domains.aaqest]
username = "barryb"
domain = ["aaqest.arl.noaa.gov"]

## Byun Configuration
[hpc_domains.byun]
username = "barryb"
domain = ["byun.arl.noaa.gov"]

